# **Affordability**

In [ ]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (676 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.9/676.9 kB 3.9 MB/s eta 0:00:00
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 12.5 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.6.1 pymongo-4.6.3

In [ ]:
#Import our dependencies
import pandas as pd
from pymongo import MongoClient
from api_keys import mongo_username, mongo_password

In [ ]:
#Connect to MongoClient Instance
connection_string = f"mongodb+srv://{mongo_username}:{mongo_password}@cluster0.9gjuly6.mongodb.net/mydatabase"
mongo = MongoClient(connection_string)

#Assign the db to a variable
db = mongo['properties']

#Assign collections to a variable
all_houses = db["all_houses"]

In [ ]:
houses_df = pd.DataFrame(list(all_houses.find()))

In [ ]:
houses_df.sample(3).T

,7846,11107,6706
_id,661ffad3b868db40d1ac5206,662001dab868db40d1ac5ecf,661ff6ffb868db40d1ac4d90
address,123 Carpaccio Ave,15 - 1120 Queens Ave,97 Elgin St W
status,Sold,Sold,Sold
latitude,-79.54883,-79.69053,-78.86939
longitude,43.84384,43.46281,43.90162
floor_size,2188.0,1699.0,NaN
bedrooms,3.0,3.0,0.0
bathrooms,5.0,3.0,6.0
garage,2.0,1.0,6.0
city,Vaughan,Oakville,Oshawa
type_of_house,Freehold Townhouse,Condo Townhouse,Multiplex
date_listed,2024-02-22 00:00:00,2023-07-10 00:00:00,2023-07-18 00:00:00
neighbourhood,Vellore Village,College Park,O'Neill
price,1198000.0,979900.0,1199000.0
sold_price,1190000.0,979900.0,1190000.0
affordable_no_down_payment,No,No,No
mortgage_insurance_eligible,No,Yes,No
down_payment,NaN,72990.0,NaN
price_minus_down_payment,NaN,906910.0,NaN
affordable_with_down_payment,No,No,No

In [ ]:
# Add 'affordable' column with no values
houses_df['affordable_no_down_payment'] = None
houses_df['affordable_no_down_payment'] = houses_df['affordable_no_down_payment'].astype('str')

In [ ]:
houses_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15359 entries, 0 to 15358
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   _id                           15359 non-null  object
 1   address                       15358 non-null  object
 2   status                        15359 non-null  object
 3   latitude                      15308 non-null  float64
 4   longitude                     15308 non-null  float64
 5   floor_size                    14833 non-null  float64
 6   bedrooms                      15262 non-null  float64
 7   bathrooms                     15314 non-null  float64
 8   garage                        15315 non-null  float64
 9   city                          15359 non-null  object
 10  type_of_house                 15359 non-null  object
 11  date_listed                   15359 non-null  datetime64[ns]
 12  neighbourhood                 15359 non-null  object
 13  price                         15317 non-null  float64
 14  sold_price                    15359 non-null  float64
 15  affordable_no_down_payment    15359 non-null  object
 16  mortgage_insurance_eligible   15359 non-null  object
 17  down_payment                  8281 non-null   float64
 18  price_minus_down_payment      8281 non-null   float64
 19  affordable_with_down_payment  15359 non-null  object
dtypes: datetime64[ns](1), float64(10), object(9)
memory usage: 2.3+ MB

In [ ]:
# mean household income is "96700"
mean_household_income = 96700

# Calculate the affordability threshold (house is affordable if it costs no more than 30% of income)
affordability_threshold = mean_household_income * 0.3

# Add results to column
houses_df['affordable_no_down_payment'] = houses_df['price'] <= affordability_threshold

# Convert boolean values to 'Yes' and 'No'
houses_df['affordable_no_down_payment'] = houses_df['affordable_no_down_payment'].map({True: 'Yes', False: 'No'})

In [ ]:
houses_df_sorted = houses_df.sort_values(by='price')
houses_df_sorted.head(15)

,_id,address,status,latitude,longitude,floor_size,bedrooms,bathrooms,garage,city,type_of_house,date_listed,neighbourhood,price,sold_price,affordable_no_down_payment,mortgage_insurance_eligible,down_payment,price_minus_down_payment,affordable_with_down_payment
3280,661c78d36a3b2f82767dcc9e,8872 9 Line,Terminated,-79.846650,43.603450,700.0,0.0,0.0,12.0,Halton Hills,Farm,2024-04-14,Rural Halton Hills,1.0,0.0,Yes,Yes,0.05,0.95,Yes
13183,662005d6b868db40d1ac66f4,4132 Hillsborough Cres,Sold,-79.746790,43.494630,2750.0,4.0,4.0,2.0,Oakville,Detached,2023-05-22,Rural Oakville,1.0,1810000.0,Yes,Yes,0.05,0.95,Yes
14510,662008a1b868db40d1ac6c27,8013 Sixth Line,Sold,-79.852673,43.559177,1750.0,3.0,1.0,1.0,Halton Hills,Detached,2023-08-29,Georgetown,1.0,1.0,Yes,Yes,0.05,0.95,Yes
14511,662008a1b868db40d1ac6c28,8029 Sixth Line,Sold,-79.853190,43.559920,2750.0,0.0,0.0,1.0,Halton Hills,Detached,2023-08-29,Georgetown,1.0,1.0,Yes,Yes,0.05,0.95,Yes
717,661893b601cd90686eeff383,203 Goddard St,For Sale,-79.452175,43.764003,2427.0,3.0,3.0,2.0,North York,Detached,2024-04-11,Bathurst Manor,1.0,0.0,Yes,Yes,0.05,0.95,Yes
427,66187be2df7d912c9b71940d,203 Goddard St,For Sale,-79.452175,43.764003,2427.0,3.0,3.0,2.0,North York,Detached,2024-04-11,Bathurst Manor,1.0,0.0,Yes,Yes,0.05,0.95,Yes
3157,661ae8c0a41112e14ca6ec60,205 - 151 Robinson Street,For Sale,-79.668757,43.444225,700.0,1.0,1.0,1.0,Oakville,Condo/Apt Unit,2024-04-13,Old Oakville,2600.0,0.0,Yes,Yes,130.00,2470.00,Yes
9025,661ffed3b868db40d1ac56a2,4182 Galileo Common,Sold,-79.774229,43.363385,1564.0,2.0,3.0,1.0,Burlington,Row/Townhouse,2024-03-03,Shoreacres,3100.0,3100.0,Yes,Yes,155.00,2945.00,Yes
105,65e3eada4625ce6cbae3a06a,503 - 5915 Yonge Street Ave,Suspended,-79.416810,43.786310,749.0,2.0,2.0,1.0,North York,Condo Apt,2024-03-02,Willowdale West,3400.0,0.0,Yes,Yes,170.00,3230.00,Yes
9026,661ffed3b868db40d1ac56a3,2472 Badger Crescent,Sold,-79.748841,43.417118,1687.0,3.0,3.0,1.0,Oakville,Row/Townhouse,2023-09-05,Glen Abbey,3500.0,3750.0,Yes,Yes,175.00,3325.00,Yes
14512,662008a1b868db40d1ac6c29,168 - 1421 Costigan Rd,Sold,-79.849480,43.526140,NaN,NaN,0.0,1.0,Milton,Parking Space,2023-06-29,Clarke,20000.0,19000.0,Yes,Yes,1000.00,19000.00,Yes
1961,661894d301cd90686eeff868,8 - 890 Sheppard Ave W,For Sale,-79.456030,43.752290,NaN,NaN,0.0,1.0,North York,Parking Space,2024-04-09,Bathurst Manor,27500.0,0.0,Yes,Yes,1375.00,26125.00,Yes
6950,661ffa3cb868db40d1ac4e86,9255 Jane St,Sold,-79.530820,43.833300,NaN,NaN,0.0,1.0,Vaughan,Parking Space,2024-03-29,Maple,29999.0,29999.0,No,Yes,1499.95,28499.05,Yes
3038,661ae8a6a41112e14ca6ebe9,2900 Highway 7,For Sale,-79.520230,43.795860,NaN,NaN,0.0,0.0,Vaughan,Parking Space,2024-04-12,Vaughan Corporate Centre,50000.0,0.0,No,Yes,2500.00,47500.00,No
9027,661ffed4b868db40d1ac56a4,3184 Spruce Ave,Sold,NaN,NaN,NaN,NaN,0.0,0.0,Burlington,Vacant Land,2024-02-29,Roseland,61000.0,50000.0,No,Yes,3050.00,57950.00,No

In [ ]:
# Only houses that are affordable
affordable_houses = houses_df[houses_df['affordable_no_down_payment'] == 'Yes']

selected_columns = ['status', 'city', 'type_of_house','price', 'affordable_no_down_payment']

# Display the DataFrame with only the selected columns
affordable_houses[selected_columns]

#print(len(affordable_houses))

,status,city,type_of_house,price,affordable_no_down_payment
105,Suspended,North York,Condo Apt,3400.0,Yes
427,For Sale,North York,Detached,1.0,Yes
717,For Sale,North York,Detached,1.0,Yes
1961,For Sale,North York,Parking Space,27500.0,Yes
3157,For Sale,Oakville,Condo/Apt Unit,2600.0,Yes
3280,Terminated,Halton Hills,Farm,1.0,Yes
9025,Sold,Burlington,Row/Townhouse,3100.0,Yes
9026,Sold,Oakville,Row/Townhouse,3500.0,Yes
13183,Sold,Oakville,Detached,1.0,Yes
14510,Sold,Halton Hills,Detached,1.0,Yes
14511,Sold,Halton Hills,Detached,1.0,Yes
14512,Sold,Milton,Parking Space,20000.0,Yes

# **Mortgage Loan Insurance**

In [ ]:
# Calculate if house is eligible for mortgage insurance
## Cost = <=$500,000; you minimum down payment of 5%.
## Cost = >$500,000; you’ll need a minimum of 5% down on the first $500,000 and 10% on the remainder
## Cost = $1,000,000+; mortgage loan insurance is not available.

In [ ]:
def calculate_loan_insurance_and_down_payment(price):
    if price <= 500000:
        mortgage_insurance_eligible = True
        down_payment = price * 0.05  # 5% down payment
    elif 500000 < price < 1000000:
        mortgage_insurance_eligible = True
        down_payment = 500000 * 0.05 + (price - 500000) * 0.10  # 5% on first $500k and 10% on the remainder
    else:
        mortgage_insurance_eligible = False
        down_payment = None  # Mortgage loan insurance is not available

    return mortgage_insurance_eligible, down_payment

# add data to DF
houses_df['mortgage_insurance_eligible'], houses_df['down_payment'] = zip(*houses_df['price'].apply(calculate_loan_insurance_and_down_payment))

# convert boolians
houses_df['mortgage_insurance_eligible'] = houses_df['mortgage_insurance_eligible'].map({True: 'Yes', False: 'No'})

In [ ]:
houses_df.head(2).T

,0,1
_id,65e3e8514625ce6cbae3942a,65e3e8514625ce6cbae3942c
address,167 Olive Ave,233 Bennet Dr
status,Sold Conditional,Sold
latitude,-78.85339,-79.51915
longitude,43.88987,43.928
floor_size,831.0,1444.0
bedrooms,1.0,3.0
bathrooms,1.0,2.0
garage,0.0,1.0
city,Oshawa,King
type_of_house,Freehold Townhouse,Detached
date_listed,2024-03-02 00:00:00,2024-03-02 00:00:00
neighbourhood,Central,King City
price,319900.0,1750000.0
sold_price,319900.0,1691000.0
affordable_no_down_payment,No,No
mortgage_insurance_eligible,Yes,No
down_payment,15995.0,NaN

In [ ]:
# Is the house now considered affordable if a person has a down payment
# price - down payment
houses_df['price_minus_down_payment'] = houses_df['price'] - houses_df['down_payment']

# Add new column based on price with downpayment
houses_df['affordable_with_down_payment'] = houses_df['price_minus_down_payment'] <= affordability_threshold

# convert boolians
houses_df['affordable_with_down_payment'] = houses_df['affordable_with_down_payment'].map({True: 'Yes', False: 'No'})

# Display the DataFrame
houses_df.head(2).T

,0,1
_id,65e3e8514625ce6cbae3942a,65e3e8514625ce6cbae3942c
address,167 Olive Ave,233 Bennet Dr
status,Sold Conditional,Sold
latitude,-78.85339,-79.51915
longitude,43.88987,43.928
floor_size,831.0,1444.0
bedrooms,1.0,3.0
bathrooms,1.0,2.0
garage,0.0,1.0
city,Oshawa,King
type_of_house,Freehold Townhouse,Detached
date_listed,2024-03-02 00:00:00,2024-03-02 00:00:00
neighbourhood,Central,King City
price,319900.0,1750000.0
sold_price,319900.0,1691000.0
affordable_no_down_payment,No,No
mortgage_insurance_eligible,Yes,No
down_payment,15995.0,NaN
price_minus_down_payment,303905.0,NaN
affordable_with_down_payment,No,No

In [ ]:
# Only houses that are affordable
affordable_houses_with_down_payment = houses_df[houses_df['affordable_with_down_payment'] == 'Yes']

selected_columns = ['status', 'city', 'type_of_house','price', 'affordable_with_down_payment']

# Display the DataFrame with only the selected columns
affordable_houses_with_down_payment[selected_columns]

,status,city,type_of_house,price,affordable_with_down_payment
105,Suspended,North York,Condo Apt,3400.0,Yes
427,For Sale,North York,Detached,1.0,Yes
717,For Sale,North York,Detached,1.0,Yes
1961,For Sale,North York,Parking Space,27500.0,Yes
3157,For Sale,Oakville,Condo/Apt Unit,2600.0,Yes
3280,Terminated,Halton Hills,Farm,1.0,Yes
6950,Sold,Vaughan,Parking Space,29999.0,Yes
9025,Sold,Burlington,Row/Townhouse,3100.0,Yes
9026,Sold,Oakville,Row/Townhouse,3500.0,Yes
13183,Sold,Oakville,Detached,1.0,Yes
14510,Sold,Halton Hills,Detached,1.0,Yes
14511,Sold,Halton Hills,Detached,1.0,Yes
14512,Sold,Milton,Parking Space,20000.0,Yes

In [ ]:
houses_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15359 entries, 0 to 15358
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   _id                           15359 non-null  object
 1   address                       15359 non-null  object
 2   status                        15359 non-null  object
 3   latitude                      15308 non-null  float64
 4   longitude                     15308 non-null  float64
 5   floor_size                    14833 non-null  float64
 6   bedrooms                      15262 non-null  float64
 7   bathrooms                     15314 non-null  float64
 8   garage                        15315 non-null  float64
 9   city                          15359 non-null  object
 10  type_of_house                 15359 non-null  object
 11  date_listed                   15359 non-null  datetime64[ns]
 12  neighbourhood                 15359 non-null  object
 13  price                         15317 non-null  float64
 14  sold_price                    15359 non-null  float64
 15  affordable_no_down_payment    15359 non-null  object
 16  mortgage_insurance_eligible   15359 non-null  object
 17  down_payment                  8281 non-null   float64
 18  price_minus_down_payment      8281 non-null   float64
 19  affordable_with_down_payment  15359 non-null  object
dtypes: datetime64[ns](1), float64(10), object(9)
memory usage: 2.3+ MB

In [ ]:
# Export df
houses_df.to_csv("houses_affordable.csv", index=False)